/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225703;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarriorTest {
    @Test 
    void warriorAttackTest() {
        int defaultWarriorHp = 100;
        int defaultWarriorAttack = 100;
        int defaultSlimeHp = 1000;
        Warrior demoWarriore = new Warrior("デモ戦士", defaultWarriorHp, defaultWarriorAttack);
        Enemy slime = new Enemy("スライムもどき", defaultSlimeHp, 100);
        for (int count=0; count<3; count++) {
            demoWarriore.attackWithWeponSkill(slime);
            assertEquals(slime.getHitPoint(), (defaultSlimeHp - defaultWarriorAttack*1.5*(count+1)));
        }
        
    }
}